---

- name: Add apache2 PPA
  apt_repository:
    repo: ppa:ondrej/apache2
    state: present
    update_cache: true

- name: apache2 is installed
  apt:
    pkg: apache2
    state: present

- name: apache2 is running
  service:
    name: apache2
    state: started
    enabled: yes

- name: enable needed modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
   - rewrite
   - proxy
   - proxy_fcgi
   - "mpm_{{ apache_mpm }}"
   - ssl
   - http2
   - brotli
  notify:
   - restart apache2
