---

- name: Configure global SSL options
  copy: src=ssl.conf dest=/etc/apache2/mods-available/ssl.conf
  notify:
   - restart apache2

- name: Ensure SSL directory for certs present
  file: path=/etc/apache2/ssl state=directory mode=0700
